FROM node:22-alpine3.20

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json .

COPY pnpm-lock.yaml .

RUN pnpm install

COPY src src

COPY public public

COPY certs certs

COPY tsconfig.json tsconfig.json

EXPOSE 8085

RUN pnpm run build

CMD [ "pnpm", "run", "dev" ]






