FROM node:22-alpine3.20 AS base

# stage 01 build image
FROM base AS builder
RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY package.json .

COPY pnpm-lock.yaml .

RUN pnpm install

COPY src src
COPY certs certs
COPY tsconfig.json tsconfig.json

RUN pnpm run build

# stage 02 runner

FROM base AS runner

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist/ dist/
COPY --from=builder /usr/src/app/package.json .
COPY --from=builder /usr/src/app/pnpm-lock.yaml .

RUN npm i -g pnpm

RUN pnpm install --prod
# Ensure the dist/server.js file is executable
RUN chmod +x dist/server.js

CMD ["pnpm", "run", "start"]



