services:
  postgres-prod:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - authpgdataprod:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - auth_service_prod_network

  auth-service-prod:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.prod
    container_name: auth-service
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '8085:8085'
    env_file:
      - .env.prod
    depends_on:
      - postgres-prod
    networks:
      - auth_service_prod_network

volumes:
  authpgdataprod:
    name: authpgdataprod

networks:
  auth_service_prod_network:
    name: auth_service_prod_network
    driver: bridge
