services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - authpgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - auth_service_network

  auth-service:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    container_name: auth-service
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '8085:8085'
    env_file:
      - .env.dev
    depends_on:
      - postgres
    networks:
      - auth_service_network

volumes:
  authpgdata:
    name: authpgdata

networks:
  auth_service_network:
    name: auth_service_network
    driver: bridge
