version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: authpg-container
    environment:
      - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    volumes:
      - authpgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: auth-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8085:8085'
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  authpgdata:
    name: authpgdata
